version: "3.8"
services:
  team:
    hostname: "team"
    #restart: always
    build: ./src
    command: python src/app.py
    volumes:
      - "./:/src"
    ports:
      - "5000:5000"
    expose:
      - "5000"
    depends_on: 
      - "database"
  
  database:
    image: mongo
    hostname: "database"
    
    volumes:
      - ./mongo-volume:/data/db
    ports:
     - '27017-27019:27017-27019'
    expose:
      - '27017-27019:27017-27019'